USE gosampledb

CREATE TABLE IF NOT EXISTS user (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	mail VARCHAR(255) NOT NULL,
	password VARCHAR(255) NOT NULL,
	authkey VARCHAR(255) NOT NULL,
	point INT UNSIGNED NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS user_purchase_history (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	user_id INT NOT NULL,
	item_id INT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS item (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	user_id INT NOT NULL,
	name VARCHAR(255) NOT NULL,
	price INT UNSIGNED NOT NULL,
	stock_flg INT UNSIGNED NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    PRIMARY KEY(id)
);